### ISSUE TITLE
HTTPclient Issues

### ISSUE THREAD

**Issue by Hye-Dev** [hb432/grakkit#11]
The Grakkit HTTPClient service does not seem to work.

My code:
const response = Spigot.core.fetch(`https://api.urbandictionary.com/v0/define?term=lol`);
            const json = response.json();

Error:
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: java.lang.IllegalAccessException: access to public member failed: sun.net.www.protocol.https.HttpsURLConnectionImpl.setDoOutput[Ljava.lang.Object;@2e385896/invokeVirtual, from public Lookup

**Comment by ghost** [comment]
The `fetch` function has been re-implemented and fixed in the latest version of `@grakkit/stdlib`. Happy get requesting!
