### ISSUE TITLE
stdlib.file() doesnt supports utf-8

### ISSUE THREAD

**Issue by TheArmagan** [hb432/grakkit#16]
Yeah the problem is stdlib.file().read or/and write doesnt support utf8.
But they should.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Heya @TheArmagan, is it possible to confirm that this is still an issue? If it is, we'll look into what can be done ^^

**Comment by ghost** [comment]
stdlib v1 isn't being updated any more, so this probably isn't gonna get fixed. however, we do intend to create a polyfill for parts the NodeJS `fs` module, and that should definitely support UTF-8!
