### ISSUE TITLE
Minor display version mismatch 

### ISSUE THREAD

**Issue by MercerK** [hb432/grakkit#22]
When running version 5.0.5 for paper, it states `Loading grakkit v5.0.3` during runtime.

May be due to https://github.com/grakkit/grakkit/blob/master/paper/src/main/resources/plugin.yml

**Comment by brayjamin** [comment]
sus!

**Comment by brayjamin** [comment]
fortunately it doesn't matter much since the last few versions have mostly been focused on Minestom and minor improvements
but yeah i committed a fix

I'm keeping the issue open until next release bc I don't feel like compiling a new version just for that xd

**Comment by ghost** [comment]
we fixed it
