### ISSUE TITLE
Grakkit failing to load on 5.0.6, Paper MC 1.18.1

### ISSUE THREAD

**Issue by MercerK** [hb432/grakkit#28]
![image](https://user-images.githubusercontent.com/13123338/154725530-02d6b65d-3641-446b-ad9d-33326c3d712d.png)

**Comment by MercerK** [comment]
Grakkit 5.0.6

MC 1.18.1

Paper 177

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

This is currently happening with the https://github.com/MercerK/grakkit-boilerplate project.

**Comment by ghost** [comment]
gaming
