### ISSUE TITLE
Nashorn compat mode conflicts with newer ES APIs

### ISSUE THREAD

**Issue by RepComm** [hb432/grakkit#4]
`setInterval` unimplemented in nashorn, so nashorn compat mod should be disabled in context construction (java plugin) code.

Conflicts with removing support:
get/set<Name> doesn't convert to getter/setter without it
Possible resolution: Implement pre-parser (could be a lot of fun!)

**Comment by grakkit** [comment]
Nashorn compatibility mode has been removed.
